on: push
name: CI/CD
jobs:
  FTP-Deploy-Action:
    name: CI&CD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '16.x'

      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package.json') }} # 缓存标识

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true' # 如果没有缓存的话
        run: npx pnpm i

      - name: Build Packages
        run: npx pnpm run content-build
